package utng.hbernate3;
// Generated 19/10/2016 11:33:55 AM by Hibernate Tools 5.2.0.Beta1

/**
 * ContactoId generated by hbm2java
 */
public class ContactoId implements java.io.Serializable {

	private int idCliente;
	private int idContacto;

	public ContactoId() {
	}

	public ContactoId(int idCliente, int idContacto) {
		this.idCliente = idCliente;
		this.idContacto = idContacto;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public int getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(int idContacto) {
		this.idContacto = idContacto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactoId))
			return false;
		ContactoId castOther = (ContactoId) other;

		return (this.getIdCliente() == castOther.getIdCliente()) && (this.getIdContacto() == castOther.getIdContacto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCliente();
		result = 37 * result + this.getIdContacto();
		return result;
	}

}
