package utng.hbernate3;
// Generated 19/10/2016 11:33:55 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private int idVenta;
	private Cliente cliente;
	private Date fecha;
	private Set ventaDetalles = new HashSet(0);

	public Venta() {
	}

	public Venta(int idVenta) {
		this.idVenta = idVenta;
	}

	public Venta(int idVenta, Cliente cliente, Date fecha, Set ventaDetalles) {
		this.idVenta = idVenta;
		this.cliente = cliente;
		this.fecha = fecha;
		this.ventaDetalles = ventaDetalles;
	}

	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getVentaDetalles() {
		return this.ventaDetalles;
	}

	public void setVentaDetalles(Set ventaDetalles) {
		this.ventaDetalles = ventaDetalles;
	}

}
