package utng.ejercicio1;
// Generated 11/10/2016 01:24:29 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointment generated by hbm2java
 */
@Entity
@Table(name = "appointment", schema = "public")
public class Appointment implements java.io.Serializable {

	private int id;
	private Affiliate affiliate;
	private Doctor doctor;
	private Date dateAndTime;
	private String service;

	public Appointment() {
	}

	public Appointment(int id) {
		this.id = id;
	}

	public Appointment(int id, Affiliate affiliate, Doctor doctor, Date dateAndTime, String service) {
		this.id = id;
		this.affiliate = affiliate;
		this.doctor = doctor;
		this.dateAndTime = dateAndTime;
		this.service = service;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "affiliate_id")
	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id")
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_and_time", length = 29)
	public Date getDateAndTime() {
		return this.dateAndTime;
	}

	public void setDateAndTime(Date dateAndTime) {
		this.dateAndTime = dateAndTime;
	}

	@Column(name = "service", length = 200)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

}
