package utng.ejercicio1;
// Generated 11/10/2016 01:24:29 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicalCenter generated by hbm2java
 */
@Entity
@Table(name = "medical_center", schema = "public")
public class MedicalCenter implements java.io.Serializable {

	private int id;
	private String address;
	private String description;
	private Set doctors = new HashSet(0);
	private Set affiliates = new HashSet(0);

	public MedicalCenter() {
	}

	public MedicalCenter(int id) {
		this.id = id;
	}

	public MedicalCenter(int id, String address, String description, Set doctors, Set affiliates) {
		this.id = id;
		this.address = address;
		this.description = description;
		this.doctors = doctors;
		this.affiliates = affiliates;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicalCenter")
	public Set getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set doctors) {
		this.doctors = doctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicalCenter")
	public Set getAffiliates() {
		return this.affiliates;
	}

	public void setAffiliates(Set affiliates) {
		this.affiliates = affiliates;
	}

}
