package utng.ejercicio1;
// Generated 11/10/2016 01:24:29 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "public")
public class Rol implements java.io.Serializable {

	private long idRol;
	private String nombre;

	public Rol() {
	}

	public Rol(long idRol) {
		this.idRol = idRol;
	}

	public Rol(long idRol, String nombre) {
		this.idRol = idRol;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id_rol", unique = true, nullable = false)
	public long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(long idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
