package utng.hibernate;
// Generated 10/10/2016 02:58:52 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Modulo generated by hbm2java
 */
public class Modulo implements java.io.Serializable {

	private long idModulo;
	private String nombre;
	private String ruta;

	public Modulo() {
	}

	public Modulo(long idModulo) {
		this.idModulo = idModulo;
	}

	public Modulo(long idModulo, String nombre, String ruta) {
		this.idModulo = idModulo;
		this.nombre = nombre;
		this.ruta = ruta;
	}

	public long getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(long idModulo) {
		this.idModulo = idModulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

}
