package utng.hibernate;
// Generated 10/10/2016 02:58:52 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private long idUsuario;
	private Rol rol;
	private String contrasenia;
	private String nombreUsuario;

	public Usuario() {
	}

	public Usuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuario(long idUsuario, Rol rol, String contrasenia, String nombreUsuario) {
		this.idUsuario = idUsuario;
		this.rol = rol;
		this.contrasenia = contrasenia;
		this.nombreUsuario = nombreUsuario;
	}

	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

}
