package utng.hibernate;
// Generated 13/10/2016 02:32:09 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto", schema = "public")
public class Contacto implements java.io.Serializable {

	private ContactoId id;
	private Cliente cliente;
	private TipoContacto tipoContacto;
	private String datoContacto;

	public Contacto() {
	}

	public Contacto(ContactoId id, Cliente cliente) {
		this.id = id;
		this.cliente = cliente;
	}

	public Contacto(ContactoId id, Cliente cliente, TipoContacto tipoContacto, String datoContacto) {
		this.id = id;
		this.cliente = cliente;
		this.tipoContacto = tipoContacto;
		this.datoContacto = datoContacto;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCliente", column = @Column(name = "id_cliente", nullable = false)),
			@AttributeOverride(name = "idContacto", column = @Column(name = "id_contacto", nullable = false)) })
	public ContactoId getId() {
		return this.id;
	}

	public void setId(ContactoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_contacto")
	public TipoContacto getTipoContacto() {
		return this.tipoContacto;
	}

	public void setTipoContacto(TipoContacto tipoContacto) {
		this.tipoContacto = tipoContacto;
	}

	@Column(name = "dato_contacto", length = 200)
	public String getDatoContacto() {
		return this.datoContacto;
	}

	public void setDatoContacto(String datoContacto) {
		this.datoContacto = datoContacto;
	}

}
