package utng.hibernate;
// Generated 13/10/2016 02:32:09 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContacto generated by hbm2java
 */
@Entity
@Table(name = "tipo_contacto", schema = "public")
public class TipoContacto implements java.io.Serializable {

	private int idTipoContacto;
	private String nombre;
	private Set<Contacto> contactos = new HashSet<Contacto>(0);

	public TipoContacto() {
	}

	public TipoContacto(int idTipoContacto) {
		this.idTipoContacto = idTipoContacto;
	}

	public TipoContacto(int idTipoContacto, String nombre, Set contactos) {
		this.idTipoContacto = idTipoContacto;
		this.nombre = nombre;
		this.contactos = contactos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_tipo_contacto", unique = true, nullable = false)
	public int getIdTipoContacto() {
		return this.idTipoContacto;
	}

	public void setIdTipoContacto(int idTipoContacto) {
		this.idTipoContacto = idTipoContacto;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContacto")
	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

}
