package utng.example1;
// Generated 11/10/2016 10:59:36 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Affiliate generated by hbm2java
 */
@Entity
@Table(name = "affiliate", schema = "public")
public class Affiliate implements java.io.Serializable {

	private int id;
	private MedicalCenter medicalCenter;
	private String password;
	private String name;
	private String address;
	private Character gender;
	private Set appointments = new HashSet(0);
	private Set issues = new HashSet(0);

	public Affiliate() {
	}

	public Affiliate(int id) {
		this.id = id;
	}

	public Affiliate(int id, MedicalCenter medicalCenter, String password, String name, String address,
			Character gender, Set appointments, Set issues) {
		this.id = id;
		this.medicalCenter = medicalCenter;
		this.password = password;
		this.name = name;
		this.address = address;
		this.gender = gender;
		this.appointments = appointments;
		this.issues = issues;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medical_center_id")
	public MedicalCenter getMedicalCenter() {
		return this.medicalCenter;
	}

	public void setMedicalCenter(MedicalCenter medicalCenter) {
		this.medicalCenter = medicalCenter;
	}

	@Column(name = "password", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "affiliate")
	public Set getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set appointments) {
		this.appointments = appointments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "affiliate")
	public Set getIssues() {
		return this.issues;
	}

	public void setIssues(Set issues) {
		this.issues = issues;
	}

}
