package utng.example1;
// Generated 11/10/2016 10:59:36 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", schema = "public")
public class Doctor implements java.io.Serializable {

	private int id;
	private MedicalCenter medicalCenter;
	private String name;
	private Date dateJoined;
	private String specialty;
	private Set appointments = new HashSet(0);

	public Doctor() {
	}

	public Doctor(int id) {
		this.id = id;
	}

	public Doctor(int id, MedicalCenter medicalCenter, String name, Date dateJoined, String specialty,
			Set appointments) {
		this.id = id;
		this.medicalCenter = medicalCenter;
		this.name = name;
		this.dateJoined = dateJoined;
		this.specialty = specialty;
		this.appointments = appointments;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medical_center_id")
	public MedicalCenter getMedicalCenter() {
		return this.medicalCenter;
	}

	public void setMedicalCenter(MedicalCenter medicalCenter) {
		this.medicalCenter = medicalCenter;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_joined", length = 13)
	public Date getDateJoined() {
		return this.dateJoined;
	}

	public void setDateJoined(Date dateJoined) {
		this.dateJoined = dateJoined;
	}

	@Column(name = "specialty", length = 50)
	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set appointments) {
		this.appointments = appointments;
	}

}
