package utng.example1;
// Generated 11/10/2016 10:59:36 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Issue generated by hbm2java
 */
@Entity
@Table(name = "issue", schema = "public")
public class Issue implements java.io.Serializable {

	private int id;
	private Affiliate affiliate;
	private String type;
	private String description;

	public Issue() {
	}

	public Issue(int id) {
		this.id = id;
	}

	public Issue(int id, Affiliate affiliate, String type, String description) {
		this.id = id;
		this.affiliate = affiliate;
		this.type = type;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "affiliate_id")
	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
