package utng.example1;
// Generated 11/10/2016 10:53:42 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment implements java.io.Serializable {

	private int id;
	private Affiliate affiliate;
	private Doctor doctor;
	private Date dateAndTime;
	private String service;

	public Appointment() {
	}

	public Appointment(int id) {
		this.id = id;
	}

	public Appointment(int id, Affiliate affiliate, Doctor doctor, Date dateAndTime, String service) {
		this.id = id;
		this.affiliate = affiliate;
		this.doctor = doctor;
		this.dateAndTime = dateAndTime;
		this.service = service;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Date getDateAndTime() {
		return this.dateAndTime;
	}

	public void setDateAndTime(Date dateAndTime) {
		this.dateAndTime = dateAndTime;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

}
