package utng.hibernate;
// Generated 18/10/2016 01:39:10 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Affiliate generated by hbm2java
 */
public class Affiliate implements java.io.Serializable {

	private int id;
	private MedicalCenter medicalCenter;
	private String password;
	private String name;
	private String address;
	private Character gender;
	private Set appointments = new HashSet(0);
	private Set issues = new HashSet(0);

	public Affiliate() {
	}

	public Affiliate(int id) {
		this.id = id;
	}

	public Affiliate(int id, MedicalCenter medicalCenter, String password, String name, String address,
			Character gender, Set appointments, Set issues) {
		this.id = id;
		this.medicalCenter = medicalCenter;
		this.password = password;
		this.name = name;
		this.address = address;
		this.gender = gender;
		this.appointments = appointments;
		this.issues = issues;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MedicalCenter getMedicalCenter() {
		return this.medicalCenter;
	}

	public void setMedicalCenter(MedicalCenter medicalCenter) {
		this.medicalCenter = medicalCenter;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public Set getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set appointments) {
		this.appointments = appointments;
	}

	public Set getIssues() {
		return this.issues;
	}

	public void setIssues(Set issues) {
		this.issues = issues;
	}

}
