package utng.hibernate;
// Generated 18/10/2016 01:39:10 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment implements java.io.Serializable {

	private int id;
	private Affiliate affiliate;
	private Doctor doctor;
	private Date dateTime;
	private String service;

	public Appointment() {
	}

	public Appointment(int id) {
		this.id = id;
	}

	public Appointment(int id, Affiliate affiliate, Doctor doctor, Date dateTime, String service) {
		this.id = id;
		this.affiliate = affiliate;
		this.doctor = doctor;
		this.dateTime = dateTime;
		this.service = service;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

}
