package utng.hibernate;
// Generated 19/10/2016 09:26:32 AM by Hibernate Tools 5.2.0.Beta1

/**
 * Contacto generated by hbm2java
 */
public class Contacto implements java.io.Serializable {

	private ContactoId id;
	private Cliente cliente;
	private TipoContacto tipoContacto;
	private String datoContacto;

	public Contacto() {
	}

	public Contacto(ContactoId id, Cliente cliente) {
		this.id = id;
		this.cliente = cliente;
	}

	public Contacto(ContactoId id, Cliente cliente, TipoContacto tipoContacto, String datoContacto) {
		this.id = id;
		this.cliente = cliente;
		this.tipoContacto = tipoContacto;
		this.datoContacto = datoContacto;
	}

	public ContactoId getId() {
		return this.id;
	}

	public void setId(ContactoId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public TipoContacto getTipoContacto() {
		return this.tipoContacto;
	}

	public void setTipoContacto(TipoContacto tipoContacto) {
		this.tipoContacto = tipoContacto;
	}

	public String getDatoContacto() {
		return this.datoContacto;
	}

	public void setDatoContacto(String datoContacto) {
		this.datoContacto = datoContacto;
	}

}
