package utng.hibernate;
// Generated 18/10/2016 01:39:10 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor implements java.io.Serializable {

	private int id;
	private MedicalCenter medicalCenter;
	private String name;
	private Date dateJoined;
	private String specialty;
	private Set appointments = new HashSet(0);

	public Doctor() {
	}

	public Doctor(int id) {
		this.id = id;
	}

	public Doctor(int id, MedicalCenter medicalCenter, String name, Date dateJoined, String specialty,
			Set appointments) {
		this.id = id;
		this.medicalCenter = medicalCenter;
		this.name = name;
		this.dateJoined = dateJoined;
		this.specialty = specialty;
		this.appointments = appointments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MedicalCenter getMedicalCenter() {
		return this.medicalCenter;
	}

	public void setMedicalCenter(MedicalCenter medicalCenter) {
		this.medicalCenter = medicalCenter;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateJoined() {
		return this.dateJoined;
	}

	public void setDateJoined(Date dateJoined) {
		this.dateJoined = dateJoined;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public Set getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set appointments) {
		this.appointments = appointments;
	}

}
