package utng.hibernate;
// Generated 18/10/2016 01:39:10 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Issue generated by hbm2java
 */
public class Issue implements java.io.Serializable {

	private int id;
	private Affiliate affiliate;
	private String type;
	private String description;

	public Issue() {
	}

	public Issue(int id) {
		this.id = id;
	}

	public Issue(int id, Affiliate affiliate, String type, String description) {
		this.id = id;
		this.affiliate = affiliate;
		this.type = type;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Affiliate getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(Affiliate affiliate) {
		this.affiliate = affiliate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
