package utng.hibernate;
// Generated 18/10/2016 01:39:10 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * MedicalCenter generated by hbm2java
 */
public class MedicalCenter implements java.io.Serializable {

	private int id;
	private String address;
	private String description;
	private Set doctors = new HashSet(0);
	private Set affiliates = new HashSet(0);

	public MedicalCenter() {
	}

	public MedicalCenter(int id) {
		this.id = id;
	}

	public MedicalCenter(int id, String address, String description, Set doctors, Set affiliates) {
		this.id = id;
		this.address = address;
		this.description = description;
		this.doctors = doctors;
		this.affiliates = affiliates;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set doctors) {
		this.doctors = doctors;
	}

	public Set getAffiliates() {
		return this.affiliates;
	}

	public void setAffiliates(Set affiliates) {
		this.affiliates = affiliates;
	}

}
