package utng.hibernate;
// Generated 19/10/2016 09:26:32 AM by Hibernate Tools 5.2.0.Beta1

/**
 * VentaDetalleId generated by hbm2java
 */
public class VentaDetalleId implements java.io.Serializable {

	private int idProducto;
	private int idVenta;

	public VentaDetalleId() {
	}

	public VentaDetalleId(int idProducto, int idVenta) {
		this.idProducto = idProducto;
		this.idVenta = idVenta;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VentaDetalleId))
			return false;
		VentaDetalleId castOther = (VentaDetalleId) other;

		return (this.getIdProducto() == castOther.getIdProducto()) && (this.getIdVenta() == castOther.getIdVenta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProducto();
		result = 37 * result + this.getIdVenta();
		return result;
	}

}
